### ISSUE TITLE
BUG: tree.hh does not compile using gcc 4.8.2

### ISSUE THREAD

**Issue by osiloke** [armadillu/ofxTimeMeasurements#2]
It seems it started from gcc 4.3 because it compiles on 4.2.x. The following error is produced:
../../../addons/ofxTimeMeasurements/src/../lib/tree.hh:67:7: error: changes meaning of ‘tree’ from ‘class treestd::basic_string<char >’ [-fpermissive]

It seems to be related to this http://c2.com/cgi/wiki?ChangesMeaningOf

**Comment by armadillu** [comment]
I removed the dependency alltogether, so I think we can close this now.
